name: Update Stanc3 submodule

on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-stanc3-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update if changed
        run: cd stanc3 && git config pull.rebase true && git pull

      - name: Commit any updates
        uses: EndBug/add-and-commit@v9
        with:
          add: 'stanc3'
